name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run pytest suite
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - uses: actions/checkout@v3
      - name: Setup Conda
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: conda-env.yml
          environment-name: metrics-logger
          init-shell: >-
            bash
          cache-environment: true
          cache-downloads: true
      - run: pytest --cache-clear --cov=src/ --cov-report term-missing --cov-report xml:coverage.xml tests/
      - uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

