name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run pytest suite
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.4
      - name: Setup Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          environment-file: conda-env.yml
          activate-environment: metrics-logger
          auto-activate-base: false
      - name: Run tests
        run: |
          pytest --cache-clear --cov=src/ --cov-report term-missing --cov-report xml:coverage.xml tests/ > pytest-coverage.txt
      - name: Echo failing test results
        if: failure()
        run: cat pytest-coverage.txt
      - name: Pytest Coverage Commenatator
        uses: coroo/pytest-coverage-commentator@v1.0.2
      - uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      