name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run pytest suite
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - uses: actions/checkout@v3
      - name: Setup Conda
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: conda-env.yml
          environment-name: metrics-logger
          init-shell: >-
            bash
          cache-environment: true
          cache-downloads: true
      - name: Run tests
        run: |
          pytest --cache-clear --cov=src/ --cov-report term-missing tests/ > pytest-coverage.txt
      - name: Echo failing test results
        if: failure()
        run: cat pytest-coverage.txt
      - name: Pytest Coverage Commenatator
        uses: coroo/pytest-coverage-commentator@v1.0.2
